In [11]:
import numpy as np
import pandas as pd

In [17]:
dataset=pd.read_csv('Data.csv')


In [19]:
dataset

Id  Country   Age   Salary Purchased
0   1  Germany  44.0  72000.0       Yes
1   2    SPAIN  76.0  45000.0        no
2   3   France  34.0  56000.0       yes
3   4  Germany  45.0  66700.0        no
4   5    SPAIN  43.0  54000.0       yes
5   6   France  23.0  78000.0        no
6   7  Germany  45.0  87000.0       yes
7   8    SPAIN  65.0      NaN        no
8   9   France   NaN  45000.0       yes

In [25]:
x=dataset[['Country','Age','Salary']].values

In [27]:
x

array([['Germany', 44.0, 72000.0],
       ['SPAIN', 76.0, 45000.0],
       ['France', 34.0, 56000.0],
       ['Germany', 45.0, 66700.0],
       ['SPAIN', 43.0, 54000.0],
       ['France', 23.0, 78000.0],
       ['Germany', 45.0, 87000.0],
       ['SPAIN', 65.0, nan],
       ['France', nan, 45000.0]], dtype=object)

In [33]:
y=dataset[['Purchased']].values

In [35]:
y

array([['Yes'],
       ['no'],
       ['yes'],
       ['no'],
       ['yes'],
       ['no'],
       ['yes'],
       ['no'],
       ['yes']], dtype=object)

In [67]:
from sklearn.impute import SimpleImputer

In [69]:
imputer=SimpleImputer(missing_values =np.nan,strategy='mean')

In [71]:
imputer=imputer.fit(x[:,1:4])

In [73]:
x[:,1:4]=imputer.transform(x[:,1:4])

In [65]:
x

array([['Germany', 44.0, 72000.0],
       ['SPAIN', 76.0, 45000.0],
       ['France', 34.0, 56000.0],
       ['Germany', 45.0, 66700.0],
       ['SPAIN', 43.0, 54000.0],
       ['France', 23.0, 78000.0],
       ['Germany', 45.0, 87000.0],
       ['SPAIN', 65.0, 62962.5],
       ['France', nan, 45000.0]], dtype=object)

In [75]:
from sklearn.preprocessing import LabelEncoder

In [83]:
label_encoder_x=LabelEncoder()

In [89]:
x[:,0]=label_encoder_x.fit_transform(x[:,0])

In [91]:
x

array([[1, 3, 72000.0],
       [2, 7, 45000.0],
       [0, 1, 56000.0],
       [1, 4, 66700.0],
       [2, 2, 54000.0],
       [0, 0, 78000.0],
       [1, 4, 87000.0],
       [2, 6, 62962.5],
       [0, 5, 45000.0]], dtype=object)

In [93]:
from sklearn.preprocessing import OneHotEncoder

In [101]:
onehotencoder=OneHotEncoder()

In [105]:
x=onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

In [107]:
x

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [109]:
labelencoder_y=LabelEncoder()

In [111]:
y=labelencoder_y.fit_transform(y)

C:\Users\GaneshChavan\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [113]:
y

array([0, 1, 2, 1, 2, 1, 2, 1, 2])

In [115]:
from sklearn.model_selection import train_test_split

In [121]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=0)

In [123]:
x_train

array([[0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [125]:
x_test

array([[0., 0., 1.],
       [1., 0., 0.]])

In [127]:
y_test

array([1, 2])

In [129]:
y_train

array([1, 2, 2, 2, 1, 0, 1])

In [134]:
from sklearn.preprocessing import StandardScaler

In [136]:
sc_x=StandardScaler()

In [138]:
x_train=sc_x.fit_transform(x_train)

In [140]:
x_test=sc_x.transform(x_test)

In [142]:
x_train

array([[-0.63245553, -0.8660254 ,  1.58113883],
       [-0.63245553, -0.8660254 ,  1.58113883],
       [ 1.58113883, -0.8660254 , -0.63245553],
       [-0.63245553,  1.15470054, -0.63245553],
       [-0.63245553,  1.15470054, -0.63245553],
       [-0.63245553,  1.15470054, -0.63245553],
       [ 1.58113883, -0.8660254 , -0.63245553]])

In [144]:
x_test

array([[-0.63245553, -0.8660254 ,  1.58113883],
       [ 1.58113883, -0.8660254 , -0.63245553]])